version: "3.9"

services:
  backend:
    build:
      context: .                # root folder contains run_tutor.sh and requirements.txt
      dockerfile: Dockerfile
    container_name: aitutor_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["bash", "run_tutor.sh"]
    volumes:
      - .:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aitutor_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
