export const string = {
    chooseNumAnswers: ({ numCorrect }: { numCorrect: string }) =>
        `Select ${numCorrect} correct answer${numCorrect !== "1" ? "s" : ""}`,
    chooseAllAnswers: "Select all correct answers",
    chooseOneAnswer: "Select one answer",
    characterCount: ({ used, num }: { used: number; num: number }) => `${used} / ${num}`,
    closeKeypad: "",
    openKeypad: "",
    mathInputBox: "",
    removeHighlight: "",
    addHighlight: "",
    hintPos: ({ pos }: { pos: number }) => `Hint ${pos}`,
    errorRendering: ({ error }: { error: string }) => `Error: ${error}`,
    graphieLabel: "",
    KhanAcademy: "",
    // Add many more missing properties
    onePoint: "",
    points: "",
    loading: "",
    checkAnswer: "",
    solution: "",
    hints: "",
    explanation: "",
    reset: "",
    all: "",
    none: "",
    getHelpWithThisExercise: "",
    reportAProblem: "",
    relatedContent: "",
    video: "",
    article: "",
    exercises: "",
    unitTest: "",
    graded: "",
    notGraded: "",
    showAllHints: "",
    hideAllHints: "",
    showHint: "",
    hideHint: "",
    viewSolution: "",
    hideSolution: "",
    continueButton: "",
    tryAgain: "",
    youGot: "",
    outOf: "",
    correct: "",
    incorrect: "",
    partiallyCorrect: "",
    yourAnswer: "",
    correctAnswer: "",
    explanationOfAnswer: "",
    ariaLabel: "",
    close: "",
    correctPrompt: "",
    incorrectPrompt: "",
    itemFeedback: "",
    problem: "",
    solutionExplanation: "",
    solutionExplanationHeading: "",
    hintsAndSolution: "",
    hintAvailable: "",
    hintsUsed: "",
    noHintsAvailable: "",
    solutionExplanationNotAvailable: "",
    solutionExplanationAvailable: "",
    solutionExplanationHeadingAvailable: "",
    solutionExplanationHeadingNotAvailable: "",
    solutionExplanationHeadingAvailableWithHints: "",
    solutionExplanationHeadingNotAvailableWithHints: "",
    solutionExplanationHeadingAvailableWithoutHints: "",
    solutionExplanationHeadingNotAvailableWithoutHints: "",
    solutionExplanationHeadingAvailableWithHintsAndSolution: "",
    solutionExplanationHeadingNotAvailableWithHintsAndSolution: "",
    solutionExplanationHeadingAvailableWithoutHintsAndSolution: "",
    solutionExplanationHeadingNotAvailableWithoutHintsAndSolution: "",
    solutionExplanationHeadingAvailableWithHintsAndNoSolution: "",
    solutionExplanationHeadingNotAvailableWithHintsAndNoSolution: "",
    solutionExplanationHeadingAvailableWithoutHintsAndNoSolution: "",
    solutionExplanationHeadingNotAvailableWithoutHintsAndNoSolution: "",
}